. ~/.bashrc

export PATH="$PATH:~/.gem/ruby/2.3.0/bin"
export GEM_HOME="$HOME:~/.gem"

export NODE_ENV={{ node_env }}
export MAILGUN_API_KEY={{ vault_mailgun_api_key }}
export MAILGUN_DOMAIN={{ top_domain }}
export INFO_EMAIL={{ info_email }}
export WEBMASTER_EMAIL={{ webmaster_email }}

export RAVEN_DSN={{ vault_raven_dsn }}

export TEST_STRIPE_PUBLIC={{ test_public_stripe_api_key }}
export TEST_STRIPE={{ test_stripe_api_key }}

export STRIPE_PUBLIC_ES={{ public_stripe_es_api_key }}
export STRIPE_PUBLIC_CA={{ public_stripe_es_api_key }}
export STRIPE_PUBLIC_EN={{ public_stripe_pt_api_key }}
export STRIPE_PUBLIC_PT={{ public_stripe_pt_api_key }}

export STRIPE_ES={{ vault_stripe_es_api_key }}
export STRIPE_CA={{ vault_stripe_es_api_key }}
export STRIPE_EN={{ vault_stripe_pt_api_key }}
export STRIPE_PT={{ vault_stripe_pt_api_key }}

export REDIS_SECRET_KEY={{ vault_redis_secret_key }}
