---

- hosts: development
  become: yes
  vars_files:
    - vars.yml
    - secrets.yml
  vars:
    domain: 'local.{{ top_domain }}'
    certificates_folder: /home/{{ user }}/shared/certificates
    node_env: development

    # Development public keys
    public_stripe_es_api_key: pk_test_NdPiBNTv4O664zYCh7W4Mcrw
    public_stripe_pt_api_key: pk_test_NdPiBNTv4O664zYCh7W4Mcrw

    # Development private keys
    vault_stripe_es_api_key: sk_test_XCQ8tR2I83v6UnxXS4yTAtjP
    vault_stripe_pt_api_key: sk_test_XCQ8tR2I83v6UnxXS4yTAtjP

  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"
      private: no

  roles:
    - common
    - frontend
    - backend

  handlers:
    - name: nginx reload
      service: name=nginx state=reloaded
