---

- hosts: production
  remote_user: dioniberica
  become: yes
  vars_files:
    - vars.yml
    - secrets.yml
  vars:
    domain: dioniberica.com
    certificates_folder: /etc/letsencrypt/live
    node_env: production
  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"

  roles:
    - common
    - frontend
    - backend
