---
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
      - python-mysqldb
      - mysql-server

  - name: Start the MySQL service
    service:
      name: mysql
      state: started
      enabled: true

  - name: Update mysql root password for all root accounts
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ vault_mysql_root_password }}"
      login_user: root
      login_password: "{{ vault_mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Creates an extra user
    mysql_user:
      name: "{{ user }}"
      password: "{{ vault_mysql_user_password }}"
      host: "%"
      priv: '*.*:ALL,GRANT'
      state: present
